// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package io.four.raft.proto;

public final class Raft {
  private Raft() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ServerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Server)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 server_id = 1;</code>
     * @return The serverId.
     */
    int getServerId();

    /**
     * <code>string host = 2;</code>
     * @return The host.
     */
    java.lang.String getHost();
    /**
     * <code>string host = 2;</code>
     * @return The bytes for host.
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <code>uint32 port = 3;</code>
     * @return The port.
     */
    int getPort();
  }
  /**
   * Protobuf type {@code Server}
   */
  public  static final class Server extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Server)
      ServerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Server.newBuilder() to construct.
    private Server(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Server() {
      host_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Server();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Server(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              serverId_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              host_ = s;
              break;
            }
            case 24: {

              port_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.four.raft.proto.Raft.internal_static_Server_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.four.raft.proto.Raft.internal_static_Server_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.four.raft.proto.Raft.Server.class, io.four.raft.proto.Raft.Server.Builder.class);
    }

    public static final int SERVER_ID_FIELD_NUMBER = 1;
    private int serverId_;
    /**
     * <code>uint32 server_id = 1;</code>
     * @return The serverId.
     */
    public int getServerId() {
      return serverId_;
    }

    public static final int HOST_FIELD_NUMBER = 2;
    private volatile java.lang.Object host_;
    /**
     * <code>string host = 2;</code>
     * @return The host.
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        host_ = s;
        return s;
      }
    }
    /**
     * <code>string host = 2;</code>
     * @return The bytes for host.
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 3;
    private int port_;
    /**
     * <code>uint32 port = 3;</code>
     * @return The port.
     */
    public int getPort() {
      return port_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (serverId_ != 0) {
        output.writeUInt32(1, serverId_);
      }
      if (!getHostBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, host_);
      }
      if (port_ != 0) {
        output.writeUInt32(3, port_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (serverId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, serverId_);
      }
      if (!getHostBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, host_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, port_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.four.raft.proto.Raft.Server)) {
        return super.equals(obj);
      }
      io.four.raft.proto.Raft.Server other = (io.four.raft.proto.Raft.Server) obj;

      if (getServerId()
          != other.getServerId()) return false;
      if (!getHost()
          .equals(other.getHost())) return false;
      if (getPort()
          != other.getPort()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getServerId();
      hash = (37 * hash) + HOST_FIELD_NUMBER;
      hash = (53 * hash) + getHost().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.four.raft.proto.Raft.Server parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.four.raft.proto.Raft.Server parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.four.raft.proto.Raft.Server parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.four.raft.proto.Raft.Server parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.four.raft.proto.Raft.Server parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.four.raft.proto.Raft.Server parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.four.raft.proto.Raft.Server parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.four.raft.proto.Raft.Server parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.four.raft.proto.Raft.Server parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.four.raft.proto.Raft.Server parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.four.raft.proto.Raft.Server parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.four.raft.proto.Raft.Server parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.four.raft.proto.Raft.Server prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Server}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Server)
        io.four.raft.proto.Raft.ServerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.four.raft.proto.Raft.internal_static_Server_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.four.raft.proto.Raft.internal_static_Server_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.four.raft.proto.Raft.Server.class, io.four.raft.proto.Raft.Server.Builder.class);
      }

      // Construct using io.four.raft.proto.Raft.Server.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        serverId_ = 0;

        host_ = "";

        port_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.four.raft.proto.Raft.internal_static_Server_descriptor;
      }

      @java.lang.Override
      public io.four.raft.proto.Raft.Server getDefaultInstanceForType() {
        return io.four.raft.proto.Raft.Server.getDefaultInstance();
      }

      @java.lang.Override
      public io.four.raft.proto.Raft.Server build() {
        io.four.raft.proto.Raft.Server result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.four.raft.proto.Raft.Server buildPartial() {
        io.four.raft.proto.Raft.Server result = new io.four.raft.proto.Raft.Server(this);
        result.serverId_ = serverId_;
        result.host_ = host_;
        result.port_ = port_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.four.raft.proto.Raft.Server) {
          return mergeFrom((io.four.raft.proto.Raft.Server)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.four.raft.proto.Raft.Server other) {
        if (other == io.four.raft.proto.Raft.Server.getDefaultInstance()) return this;
        if (other.getServerId() != 0) {
          setServerId(other.getServerId());
        }
        if (!other.getHost().isEmpty()) {
          host_ = other.host_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.four.raft.proto.Raft.Server parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.four.raft.proto.Raft.Server) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int serverId_ ;
      /**
       * <code>uint32 server_id = 1;</code>
       * @return The serverId.
       */
      public int getServerId() {
        return serverId_;
      }
      /**
       * <code>uint32 server_id = 1;</code>
       * @param value The serverId to set.
       * @return This builder for chaining.
       */
      public Builder setServerId(int value) {
        
        serverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 server_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerId() {
        
        serverId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object host_ = "";
      /**
       * <code>string host = 2;</code>
       * @return The host.
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string host = 2;</code>
       * @return The bytes for host.
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string host = 2;</code>
       * @param value The host to set.
       * @return This builder for chaining.
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string host = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearHost() {
        
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>string host = 2;</code>
       * @param value The bytes for host to set.
       * @return This builder for chaining.
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        host_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>uint32 port = 3;</code>
       * @return The port.
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>uint32 port = 3;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 port = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Server)
    }

    // @@protoc_insertion_point(class_scope:Server)
    private static final io.four.raft.proto.Raft.Server DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.four.raft.proto.Raft.Server();
    }

    public static io.four.raft.proto.Raft.Server getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Server>
        PARSER = new com.google.protobuf.AbstractParser<Server>() {
      @java.lang.Override
      public Server parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Server(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Server> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Server> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.four.raft.proto.Raft.Server getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VoteRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VoteRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 请求选票的候选人的 Id
     * </pre>
     *
     * <code>uint32 server_id = 1;</code>
     * @return The serverId.
     */
    int getServerId();

    /**
     * <pre>
     * 候选人的任期号
     * </pre>
     *
     * <code>uint64 term = 2;</code>
     * @return The term.
     */
    long getTerm();

    /**
     * <pre>
     * 候选人的最后日志条目的任期号
     * </pre>
     *
     * <code>uint64 last_log_term = 3;</code>
     * @return The lastLogTerm.
     */
    long getLastLogTerm();

    /**
     * <pre>
     * 候选人最后日志条目的索引值
     * </pre>
     *
     * <code>uint64 last_log_index = 4;</code>
     * @return The lastLogIndex.
     */
    long getLastLogIndex();
  }
  /**
   * Protobuf type {@code VoteRequest}
   */
  public  static final class VoteRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:VoteRequest)
      VoteRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VoteRequest.newBuilder() to construct.
    private VoteRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VoteRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new VoteRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VoteRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              serverId_ = input.readUInt32();
              break;
            }
            case 16: {

              term_ = input.readUInt64();
              break;
            }
            case 24: {

              lastLogTerm_ = input.readUInt64();
              break;
            }
            case 32: {

              lastLogIndex_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.four.raft.proto.Raft.internal_static_VoteRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.four.raft.proto.Raft.internal_static_VoteRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.four.raft.proto.Raft.VoteRequest.class, io.four.raft.proto.Raft.VoteRequest.Builder.class);
    }

    public static final int SERVER_ID_FIELD_NUMBER = 1;
    private int serverId_;
    /**
     * <pre>
     * 请求选票的候选人的 Id
     * </pre>
     *
     * <code>uint32 server_id = 1;</code>
     * @return The serverId.
     */
    public int getServerId() {
      return serverId_;
    }

    public static final int TERM_FIELD_NUMBER = 2;
    private long term_;
    /**
     * <pre>
     * 候选人的任期号
     * </pre>
     *
     * <code>uint64 term = 2;</code>
     * @return The term.
     */
    public long getTerm() {
      return term_;
    }

    public static final int LAST_LOG_TERM_FIELD_NUMBER = 3;
    private long lastLogTerm_;
    /**
     * <pre>
     * 候选人的最后日志条目的任期号
     * </pre>
     *
     * <code>uint64 last_log_term = 3;</code>
     * @return The lastLogTerm.
     */
    public long getLastLogTerm() {
      return lastLogTerm_;
    }

    public static final int LAST_LOG_INDEX_FIELD_NUMBER = 4;
    private long lastLogIndex_;
    /**
     * <pre>
     * 候选人最后日志条目的索引值
     * </pre>
     *
     * <code>uint64 last_log_index = 4;</code>
     * @return The lastLogIndex.
     */
    public long getLastLogIndex() {
      return lastLogIndex_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (serverId_ != 0) {
        output.writeUInt32(1, serverId_);
      }
      if (term_ != 0L) {
        output.writeUInt64(2, term_);
      }
      if (lastLogTerm_ != 0L) {
        output.writeUInt64(3, lastLogTerm_);
      }
      if (lastLogIndex_ != 0L) {
        output.writeUInt64(4, lastLogIndex_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (serverId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, serverId_);
      }
      if (term_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, term_);
      }
      if (lastLogTerm_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, lastLogTerm_);
      }
      if (lastLogIndex_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, lastLogIndex_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.four.raft.proto.Raft.VoteRequest)) {
        return super.equals(obj);
      }
      io.four.raft.proto.Raft.VoteRequest other = (io.four.raft.proto.Raft.VoteRequest) obj;

      if (getServerId()
          != other.getServerId()) return false;
      if (getTerm()
          != other.getTerm()) return false;
      if (getLastLogTerm()
          != other.getLastLogTerm()) return false;
      if (getLastLogIndex()
          != other.getLastLogIndex()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getServerId();
      hash = (37 * hash) + TERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTerm());
      hash = (37 * hash) + LAST_LOG_TERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastLogTerm());
      hash = (37 * hash) + LAST_LOG_INDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastLogIndex());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.four.raft.proto.Raft.VoteRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.four.raft.proto.Raft.VoteRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.four.raft.proto.Raft.VoteRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.four.raft.proto.Raft.VoteRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.four.raft.proto.Raft.VoteRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.four.raft.proto.Raft.VoteRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.four.raft.proto.Raft.VoteRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.four.raft.proto.Raft.VoteRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.four.raft.proto.Raft.VoteRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.four.raft.proto.Raft.VoteRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.four.raft.proto.Raft.VoteRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.four.raft.proto.Raft.VoteRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.four.raft.proto.Raft.VoteRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VoteRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VoteRequest)
        io.four.raft.proto.Raft.VoteRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.four.raft.proto.Raft.internal_static_VoteRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.four.raft.proto.Raft.internal_static_VoteRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.four.raft.proto.Raft.VoteRequest.class, io.four.raft.proto.Raft.VoteRequest.Builder.class);
      }

      // Construct using io.four.raft.proto.Raft.VoteRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        serverId_ = 0;

        term_ = 0L;

        lastLogTerm_ = 0L;

        lastLogIndex_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.four.raft.proto.Raft.internal_static_VoteRequest_descriptor;
      }

      @java.lang.Override
      public io.four.raft.proto.Raft.VoteRequest getDefaultInstanceForType() {
        return io.four.raft.proto.Raft.VoteRequest.getDefaultInstance();
      }

      @java.lang.Override
      public io.four.raft.proto.Raft.VoteRequest build() {
        io.four.raft.proto.Raft.VoteRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.four.raft.proto.Raft.VoteRequest buildPartial() {
        io.four.raft.proto.Raft.VoteRequest result = new io.four.raft.proto.Raft.VoteRequest(this);
        result.serverId_ = serverId_;
        result.term_ = term_;
        result.lastLogTerm_ = lastLogTerm_;
        result.lastLogIndex_ = lastLogIndex_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.four.raft.proto.Raft.VoteRequest) {
          return mergeFrom((io.four.raft.proto.Raft.VoteRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.four.raft.proto.Raft.VoteRequest other) {
        if (other == io.four.raft.proto.Raft.VoteRequest.getDefaultInstance()) return this;
        if (other.getServerId() != 0) {
          setServerId(other.getServerId());
        }
        if (other.getTerm() != 0L) {
          setTerm(other.getTerm());
        }
        if (other.getLastLogTerm() != 0L) {
          setLastLogTerm(other.getLastLogTerm());
        }
        if (other.getLastLogIndex() != 0L) {
          setLastLogIndex(other.getLastLogIndex());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.four.raft.proto.Raft.VoteRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.four.raft.proto.Raft.VoteRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int serverId_ ;
      /**
       * <pre>
       * 请求选票的候选人的 Id
       * </pre>
       *
       * <code>uint32 server_id = 1;</code>
       * @return The serverId.
       */
      public int getServerId() {
        return serverId_;
      }
      /**
       * <pre>
       * 请求选票的候选人的 Id
       * </pre>
       *
       * <code>uint32 server_id = 1;</code>
       * @param value The serverId to set.
       * @return This builder for chaining.
       */
      public Builder setServerId(int value) {
        
        serverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求选票的候选人的 Id
       * </pre>
       *
       * <code>uint32 server_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerId() {
        
        serverId_ = 0;
        onChanged();
        return this;
      }

      private long term_ ;
      /**
       * <pre>
       * 候选人的任期号
       * </pre>
       *
       * <code>uint64 term = 2;</code>
       * @return The term.
       */
      public long getTerm() {
        return term_;
      }
      /**
       * <pre>
       * 候选人的任期号
       * </pre>
       *
       * <code>uint64 term = 2;</code>
       * @param value The term to set.
       * @return This builder for chaining.
       */
      public Builder setTerm(long value) {
        
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 候选人的任期号
       * </pre>
       *
       * <code>uint64 term = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerm() {
        
        term_ = 0L;
        onChanged();
        return this;
      }

      private long lastLogTerm_ ;
      /**
       * <pre>
       * 候选人的最后日志条目的任期号
       * </pre>
       *
       * <code>uint64 last_log_term = 3;</code>
       * @return The lastLogTerm.
       */
      public long getLastLogTerm() {
        return lastLogTerm_;
      }
      /**
       * <pre>
       * 候选人的最后日志条目的任期号
       * </pre>
       *
       * <code>uint64 last_log_term = 3;</code>
       * @param value The lastLogTerm to set.
       * @return This builder for chaining.
       */
      public Builder setLastLogTerm(long value) {
        
        lastLogTerm_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 候选人的最后日志条目的任期号
       * </pre>
       *
       * <code>uint64 last_log_term = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastLogTerm() {
        
        lastLogTerm_ = 0L;
        onChanged();
        return this;
      }

      private long lastLogIndex_ ;
      /**
       * <pre>
       * 候选人最后日志条目的索引值
       * </pre>
       *
       * <code>uint64 last_log_index = 4;</code>
       * @return The lastLogIndex.
       */
      public long getLastLogIndex() {
        return lastLogIndex_;
      }
      /**
       * <pre>
       * 候选人最后日志条目的索引值
       * </pre>
       *
       * <code>uint64 last_log_index = 4;</code>
       * @param value The lastLogIndex to set.
       * @return This builder for chaining.
       */
      public Builder setLastLogIndex(long value) {
        
        lastLogIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 候选人最后日志条目的索引值
       * </pre>
       *
       * <code>uint64 last_log_index = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastLogIndex() {
        
        lastLogIndex_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:VoteRequest)
    }

    // @@protoc_insertion_point(class_scope:VoteRequest)
    private static final io.four.raft.proto.Raft.VoteRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.four.raft.proto.Raft.VoteRequest();
    }

    public static io.four.raft.proto.Raft.VoteRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VoteRequest>
        PARSER = new com.google.protobuf.AbstractParser<VoteRequest>() {
      @java.lang.Override
      public VoteRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VoteRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VoteRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VoteRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.four.raft.proto.Raft.VoteRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VoteResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VoteResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 当前任期号，以便于候选人去更新自己的任期号
     * </pre>
     *
     * <code>uint64 term = 1;</code>
     * @return The term.
     */
    long getTerm();

    /**
     * <pre>
     * 候选人赢得了此张选票时为真
     * </pre>
     *
     * <code>bool granted = 2;</code>
     * @return The granted.
     */
    boolean getGranted();
  }
  /**
   * Protobuf type {@code VoteResponse}
   */
  public  static final class VoteResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:VoteResponse)
      VoteResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VoteResponse.newBuilder() to construct.
    private VoteResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VoteResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new VoteResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VoteResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              term_ = input.readUInt64();
              break;
            }
            case 16: {

              granted_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.four.raft.proto.Raft.internal_static_VoteResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.four.raft.proto.Raft.internal_static_VoteResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.four.raft.proto.Raft.VoteResponse.class, io.four.raft.proto.Raft.VoteResponse.Builder.class);
    }

    public static final int TERM_FIELD_NUMBER = 1;
    private long term_;
    /**
     * <pre>
     * 当前任期号，以便于候选人去更新自己的任期号
     * </pre>
     *
     * <code>uint64 term = 1;</code>
     * @return The term.
     */
    public long getTerm() {
      return term_;
    }

    public static final int GRANTED_FIELD_NUMBER = 2;
    private boolean granted_;
    /**
     * <pre>
     * 候选人赢得了此张选票时为真
     * </pre>
     *
     * <code>bool granted = 2;</code>
     * @return The granted.
     */
    public boolean getGranted() {
      return granted_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (term_ != 0L) {
        output.writeUInt64(1, term_);
      }
      if (granted_ != false) {
        output.writeBool(2, granted_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (term_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, term_);
      }
      if (granted_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, granted_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.four.raft.proto.Raft.VoteResponse)) {
        return super.equals(obj);
      }
      io.four.raft.proto.Raft.VoteResponse other = (io.four.raft.proto.Raft.VoteResponse) obj;

      if (getTerm()
          != other.getTerm()) return false;
      if (getGranted()
          != other.getGranted()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTerm());
      hash = (37 * hash) + GRANTED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getGranted());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.four.raft.proto.Raft.VoteResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.four.raft.proto.Raft.VoteResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.four.raft.proto.Raft.VoteResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.four.raft.proto.Raft.VoteResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.four.raft.proto.Raft.VoteResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.four.raft.proto.Raft.VoteResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.four.raft.proto.Raft.VoteResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.four.raft.proto.Raft.VoteResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.four.raft.proto.Raft.VoteResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.four.raft.proto.Raft.VoteResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.four.raft.proto.Raft.VoteResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.four.raft.proto.Raft.VoteResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.four.raft.proto.Raft.VoteResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VoteResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VoteResponse)
        io.four.raft.proto.Raft.VoteResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.four.raft.proto.Raft.internal_static_VoteResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.four.raft.proto.Raft.internal_static_VoteResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.four.raft.proto.Raft.VoteResponse.class, io.four.raft.proto.Raft.VoteResponse.Builder.class);
      }

      // Construct using io.four.raft.proto.Raft.VoteResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        term_ = 0L;

        granted_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.four.raft.proto.Raft.internal_static_VoteResponse_descriptor;
      }

      @java.lang.Override
      public io.four.raft.proto.Raft.VoteResponse getDefaultInstanceForType() {
        return io.four.raft.proto.Raft.VoteResponse.getDefaultInstance();
      }

      @java.lang.Override
      public io.four.raft.proto.Raft.VoteResponse build() {
        io.four.raft.proto.Raft.VoteResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.four.raft.proto.Raft.VoteResponse buildPartial() {
        io.four.raft.proto.Raft.VoteResponse result = new io.four.raft.proto.Raft.VoteResponse(this);
        result.term_ = term_;
        result.granted_ = granted_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.four.raft.proto.Raft.VoteResponse) {
          return mergeFrom((io.four.raft.proto.Raft.VoteResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.four.raft.proto.Raft.VoteResponse other) {
        if (other == io.four.raft.proto.Raft.VoteResponse.getDefaultInstance()) return this;
        if (other.getTerm() != 0L) {
          setTerm(other.getTerm());
        }
        if (other.getGranted() != false) {
          setGranted(other.getGranted());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.four.raft.proto.Raft.VoteResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.four.raft.proto.Raft.VoteResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long term_ ;
      /**
       * <pre>
       * 当前任期号，以便于候选人去更新自己的任期号
       * </pre>
       *
       * <code>uint64 term = 1;</code>
       * @return The term.
       */
      public long getTerm() {
        return term_;
      }
      /**
       * <pre>
       * 当前任期号，以便于候选人去更新自己的任期号
       * </pre>
       *
       * <code>uint64 term = 1;</code>
       * @param value The term to set.
       * @return This builder for chaining.
       */
      public Builder setTerm(long value) {
        
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 当前任期号，以便于候选人去更新自己的任期号
       * </pre>
       *
       * <code>uint64 term = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerm() {
        
        term_ = 0L;
        onChanged();
        return this;
      }

      private boolean granted_ ;
      /**
       * <pre>
       * 候选人赢得了此张选票时为真
       * </pre>
       *
       * <code>bool granted = 2;</code>
       * @return The granted.
       */
      public boolean getGranted() {
        return granted_;
      }
      /**
       * <pre>
       * 候选人赢得了此张选票时为真
       * </pre>
       *
       * <code>bool granted = 2;</code>
       * @param value The granted to set.
       * @return This builder for chaining.
       */
      public Builder setGranted(boolean value) {
        
        granted_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 候选人赢得了此张选票时为真
       * </pre>
       *
       * <code>bool granted = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearGranted() {
        
        granted_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:VoteResponse)
    }

    // @@protoc_insertion_point(class_scope:VoteResponse)
    private static final io.four.raft.proto.Raft.VoteResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.four.raft.proto.Raft.VoteResponse();
    }

    public static io.four.raft.proto.Raft.VoteResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VoteResponse>
        PARSER = new com.google.protobuf.AbstractParser<VoteResponse>() {
      @java.lang.Override
      public VoteResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VoteResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VoteResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VoteResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.four.raft.proto.Raft.VoteResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ClusterConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClusterConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Server servers = 1;</code>
     */
    java.util.List<io.four.raft.proto.Raft.Server> 
        getServersList();
    /**
     * <code>repeated .Server servers = 1;</code>
     */
    io.four.raft.proto.Raft.Server getServers(int index);
    /**
     * <code>repeated .Server servers = 1;</code>
     */
    int getServersCount();
    /**
     * <code>repeated .Server servers = 1;</code>
     */
    java.util.List<? extends io.four.raft.proto.Raft.ServerOrBuilder> 
        getServersOrBuilderList();
    /**
     * <code>repeated .Server servers = 1;</code>
     */
    io.four.raft.proto.Raft.ServerOrBuilder getServersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ClusterConfig}
   */
  public  static final class ClusterConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ClusterConfig)
      ClusterConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClusterConfig.newBuilder() to construct.
    private ClusterConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClusterConfig() {
      servers_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ClusterConfig();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClusterConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                servers_ = new java.util.ArrayList<io.four.raft.proto.Raft.Server>();
                mutable_bitField0_ |= 0x00000001;
              }
              servers_.add(
                  input.readMessage(io.four.raft.proto.Raft.Server.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          servers_ = java.util.Collections.unmodifiableList(servers_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.four.raft.proto.Raft.internal_static_ClusterConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.four.raft.proto.Raft.internal_static_ClusterConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.four.raft.proto.Raft.ClusterConfig.class, io.four.raft.proto.Raft.ClusterConfig.Builder.class);
    }

    public static final int SERVERS_FIELD_NUMBER = 1;
    private java.util.List<io.four.raft.proto.Raft.Server> servers_;
    /**
     * <code>repeated .Server servers = 1;</code>
     */
    public java.util.List<io.four.raft.proto.Raft.Server> getServersList() {
      return servers_;
    }
    /**
     * <code>repeated .Server servers = 1;</code>
     */
    public java.util.List<? extends io.four.raft.proto.Raft.ServerOrBuilder> 
        getServersOrBuilderList() {
      return servers_;
    }
    /**
     * <code>repeated .Server servers = 1;</code>
     */
    public int getServersCount() {
      return servers_.size();
    }
    /**
     * <code>repeated .Server servers = 1;</code>
     */
    public io.four.raft.proto.Raft.Server getServers(int index) {
      return servers_.get(index);
    }
    /**
     * <code>repeated .Server servers = 1;</code>
     */
    public io.four.raft.proto.Raft.ServerOrBuilder getServersOrBuilder(
        int index) {
      return servers_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < servers_.size(); i++) {
        output.writeMessage(1, servers_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < servers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, servers_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.four.raft.proto.Raft.ClusterConfig)) {
        return super.equals(obj);
      }
      io.four.raft.proto.Raft.ClusterConfig other = (io.four.raft.proto.Raft.ClusterConfig) obj;

      if (!getServersList()
          .equals(other.getServersList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getServersCount() > 0) {
        hash = (37 * hash) + SERVERS_FIELD_NUMBER;
        hash = (53 * hash) + getServersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.four.raft.proto.Raft.ClusterConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.four.raft.proto.Raft.ClusterConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.four.raft.proto.Raft.ClusterConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.four.raft.proto.Raft.ClusterConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.four.raft.proto.Raft.ClusterConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.four.raft.proto.Raft.ClusterConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.four.raft.proto.Raft.ClusterConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.four.raft.proto.Raft.ClusterConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.four.raft.proto.Raft.ClusterConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.four.raft.proto.Raft.ClusterConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.four.raft.proto.Raft.ClusterConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.four.raft.proto.Raft.ClusterConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.four.raft.proto.Raft.ClusterConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClusterConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClusterConfig)
        io.four.raft.proto.Raft.ClusterConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.four.raft.proto.Raft.internal_static_ClusterConfig_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.four.raft.proto.Raft.internal_static_ClusterConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.four.raft.proto.Raft.ClusterConfig.class, io.four.raft.proto.Raft.ClusterConfig.Builder.class);
      }

      // Construct using io.four.raft.proto.Raft.ClusterConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getServersFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (serversBuilder_ == null) {
          servers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          serversBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.four.raft.proto.Raft.internal_static_ClusterConfig_descriptor;
      }

      @java.lang.Override
      public io.four.raft.proto.Raft.ClusterConfig getDefaultInstanceForType() {
        return io.four.raft.proto.Raft.ClusterConfig.getDefaultInstance();
      }

      @java.lang.Override
      public io.four.raft.proto.Raft.ClusterConfig build() {
        io.four.raft.proto.Raft.ClusterConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.four.raft.proto.Raft.ClusterConfig buildPartial() {
        io.four.raft.proto.Raft.ClusterConfig result = new io.four.raft.proto.Raft.ClusterConfig(this);
        int from_bitField0_ = bitField0_;
        if (serversBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            servers_ = java.util.Collections.unmodifiableList(servers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.servers_ = servers_;
        } else {
          result.servers_ = serversBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.four.raft.proto.Raft.ClusterConfig) {
          return mergeFrom((io.four.raft.proto.Raft.ClusterConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.four.raft.proto.Raft.ClusterConfig other) {
        if (other == io.four.raft.proto.Raft.ClusterConfig.getDefaultInstance()) return this;
        if (serversBuilder_ == null) {
          if (!other.servers_.isEmpty()) {
            if (servers_.isEmpty()) {
              servers_ = other.servers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureServersIsMutable();
              servers_.addAll(other.servers_);
            }
            onChanged();
          }
        } else {
          if (!other.servers_.isEmpty()) {
            if (serversBuilder_.isEmpty()) {
              serversBuilder_.dispose();
              serversBuilder_ = null;
              servers_ = other.servers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              serversBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getServersFieldBuilder() : null;
            } else {
              serversBuilder_.addAllMessages(other.servers_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.four.raft.proto.Raft.ClusterConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.four.raft.proto.Raft.ClusterConfig) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<io.four.raft.proto.Raft.Server> servers_ =
        java.util.Collections.emptyList();
      private void ensureServersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          servers_ = new java.util.ArrayList<io.four.raft.proto.Raft.Server>(servers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.four.raft.proto.Raft.Server, io.four.raft.proto.Raft.Server.Builder, io.four.raft.proto.Raft.ServerOrBuilder> serversBuilder_;

      /**
       * <code>repeated .Server servers = 1;</code>
       */
      public java.util.List<io.four.raft.proto.Raft.Server> getServersList() {
        if (serversBuilder_ == null) {
          return java.util.Collections.unmodifiableList(servers_);
        } else {
          return serversBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Server servers = 1;</code>
       */
      public int getServersCount() {
        if (serversBuilder_ == null) {
          return servers_.size();
        } else {
          return serversBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Server servers = 1;</code>
       */
      public io.four.raft.proto.Raft.Server getServers(int index) {
        if (serversBuilder_ == null) {
          return servers_.get(index);
        } else {
          return serversBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Server servers = 1;</code>
       */
      public Builder setServers(
          int index, io.four.raft.proto.Raft.Server value) {
        if (serversBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureServersIsMutable();
          servers_.set(index, value);
          onChanged();
        } else {
          serversBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Server servers = 1;</code>
       */
      public Builder setServers(
          int index, io.four.raft.proto.Raft.Server.Builder builderForValue) {
        if (serversBuilder_ == null) {
          ensureServersIsMutable();
          servers_.set(index, builderForValue.build());
          onChanged();
        } else {
          serversBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Server servers = 1;</code>
       */
      public Builder addServers(io.four.raft.proto.Raft.Server value) {
        if (serversBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureServersIsMutable();
          servers_.add(value);
          onChanged();
        } else {
          serversBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Server servers = 1;</code>
       */
      public Builder addServers(
          int index, io.four.raft.proto.Raft.Server value) {
        if (serversBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureServersIsMutable();
          servers_.add(index, value);
          onChanged();
        } else {
          serversBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Server servers = 1;</code>
       */
      public Builder addServers(
          io.four.raft.proto.Raft.Server.Builder builderForValue) {
        if (serversBuilder_ == null) {
          ensureServersIsMutable();
          servers_.add(builderForValue.build());
          onChanged();
        } else {
          serversBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Server servers = 1;</code>
       */
      public Builder addServers(
          int index, io.four.raft.proto.Raft.Server.Builder builderForValue) {
        if (serversBuilder_ == null) {
          ensureServersIsMutable();
          servers_.add(index, builderForValue.build());
          onChanged();
        } else {
          serversBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Server servers = 1;</code>
       */
      public Builder addAllServers(
          java.lang.Iterable<? extends io.four.raft.proto.Raft.Server> values) {
        if (serversBuilder_ == null) {
          ensureServersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, servers_);
          onChanged();
        } else {
          serversBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Server servers = 1;</code>
       */
      public Builder clearServers() {
        if (serversBuilder_ == null) {
          servers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          serversBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Server servers = 1;</code>
       */
      public Builder removeServers(int index) {
        if (serversBuilder_ == null) {
          ensureServersIsMutable();
          servers_.remove(index);
          onChanged();
        } else {
          serversBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Server servers = 1;</code>
       */
      public io.four.raft.proto.Raft.Server.Builder getServersBuilder(
          int index) {
        return getServersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Server servers = 1;</code>
       */
      public io.four.raft.proto.Raft.ServerOrBuilder getServersOrBuilder(
          int index) {
        if (serversBuilder_ == null) {
          return servers_.get(index);  } else {
          return serversBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Server servers = 1;</code>
       */
      public java.util.List<? extends io.four.raft.proto.Raft.ServerOrBuilder> 
           getServersOrBuilderList() {
        if (serversBuilder_ != null) {
          return serversBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(servers_);
        }
      }
      /**
       * <code>repeated .Server servers = 1;</code>
       */
      public io.four.raft.proto.Raft.Server.Builder addServersBuilder() {
        return getServersFieldBuilder().addBuilder(
            io.four.raft.proto.Raft.Server.getDefaultInstance());
      }
      /**
       * <code>repeated .Server servers = 1;</code>
       */
      public io.four.raft.proto.Raft.Server.Builder addServersBuilder(
          int index) {
        return getServersFieldBuilder().addBuilder(
            index, io.four.raft.proto.Raft.Server.getDefaultInstance());
      }
      /**
       * <code>repeated .Server servers = 1;</code>
       */
      public java.util.List<io.four.raft.proto.Raft.Server.Builder> 
           getServersBuilderList() {
        return getServersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.four.raft.proto.Raft.Server, io.four.raft.proto.Raft.Server.Builder, io.four.raft.proto.Raft.ServerOrBuilder> 
          getServersFieldBuilder() {
        if (serversBuilder_ == null) {
          serversBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              io.four.raft.proto.Raft.Server, io.four.raft.proto.Raft.Server.Builder, io.four.raft.proto.Raft.ServerOrBuilder>(
                  servers_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          servers_ = null;
        }
        return serversBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ClusterConfig)
    }

    // @@protoc_insertion_point(class_scope:ClusterConfig)
    private static final io.four.raft.proto.Raft.ClusterConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.four.raft.proto.Raft.ClusterConfig();
    }

    public static io.four.raft.proto.Raft.ClusterConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClusterConfig>
        PARSER = new com.google.protobuf.AbstractParser<ClusterConfig>() {
      @java.lang.Override
      public ClusterConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClusterConfig(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClusterConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClusterConfig> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.four.raft.proto.Raft.ClusterConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Server_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Server_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VoteRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VoteRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VoteResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VoteResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClusterConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClusterConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nraft.proto\"7\n\006Server\022\021\n\tserver_id\030\001 \001(" +
      "\r\022\014\n\004host\030\002 \001(\t\022\014\n\004port\030\003 \001(\r\"]\n\013VoteReq" +
      "uest\022\021\n\tserver_id\030\001 \001(\r\022\014\n\004term\030\002 \001(\004\022\025\n" +
      "\rlast_log_term\030\003 \001(\004\022\026\n\016last_log_index\030\004" +
      " \001(\004\"-\n\014VoteResponse\022\014\n\004term\030\001 \001(\004\022\017\n\007gr" +
      "anted\030\002 \001(\010\")\n\rClusterConfig\022\030\n\007servers\030" +
      "\001 \003(\0132\007.ServerB\032\n\022io.four.raft.protoB\004Ra" +
      "ftb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Server_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Server_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Server_descriptor,
        new java.lang.String[] { "ServerId", "Host", "Port", });
    internal_static_VoteRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_VoteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VoteRequest_descriptor,
        new java.lang.String[] { "ServerId", "Term", "LastLogTerm", "LastLogIndex", });
    internal_static_VoteResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_VoteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VoteResponse_descriptor,
        new java.lang.String[] { "Term", "Granted", });
    internal_static_ClusterConfig_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ClusterConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClusterConfig_descriptor,
        new java.lang.String[] { "Servers", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
